In [10]:
#hide
options(jupyter.plot_scale = 3)
options(jupyter.display_mimetypes = c("text/html"))
options(jupyter.rich_display=FALSE)
options(repr.plot.width=6, repr.plot.height=6, repr.plot.res=300)
options(max.print=1000)

# "R : matrix"
> "전북대학교 R입문 7주차 필기"

- toc: true
- branch: master
- badges: true
- comments: true
- author: Kim Jeewoo
- categories: [Introduction to R]
- image: images/r_logo.PNG

# 매트릭스를 선언하는 방법

## 방법1 : row-vector -> rbind

In [11]:
rbind(c(1,2,3,4),c(2,3,4,5))

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 2    3    4    5   

## 방법2 : column-vector -> cbind

In [12]:
cbind(c(1,2,3,4),c(2,3,4,5))

     [,1] [,2]
[1,] 1    2   
[2,] 2    3   
[3,] 3    4   
[4,] 4    5   

# 매트릭스의 차원(dimension)

In [13]:
A = rbind(c(1,2,3,4),c(2,3,4,5))
dim(A)

[1] 2 4

In [14]:
B = cbind(c(1,2,3,4),c(2,3,4,5))
dim(B)

[1] 4 2

- 차원을 바꿀 수도 있다.

In [15]:
B

     [,1] [,2]
[1,] 1    2   
[2,] 2    3   
[3,] 3    4   
[4,] 4    5   

In [16]:
dim(B) = c(2,4)

In [17]:
B

     [,1] [,2] [,3] [,4]
[1,] 1    3    2    4   
[2,] 2    4    3    5   

# 매트릭스의 원소를 뽑는 방법

In [18]:
A = rbind(c(1,2,3,4),c(5,6,7,8),c(9,10,11,12))
A

     [,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12  

In [19]:
A[1,] # 1행을 뽑고싶다.

[1] 1 2 3 4

In [20]:
A[,1] # 1열을 뽑고싶다.

[1] 1 5 9

In [21]:
A[, c(1,4)] # 1열, 4열을 뽑고싶다.

     [,1] [,2]
[1,] 1     4  
[2,] 5     8  
[3,] 9    12  

In [22]:
A[c(1,2),] # 1행, 2행을 뽑고싶다.

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8   

In [23]:
A[2,3]  # 2행3열의 원소를 뽑고싶다.

[1] 7

# apply 함수

```r
apply(matrix, 1, 특정함수)
```

를 쓰면 어떠한 특정한수가 각각의 row에 적용되어서 결과가 array로 저장된다.

여기에서 특정함수는 "벡터입력-스칼라출력"이라고 생각하자, 즉 벡터입력-스칼라입력인 함수를 적용할 수 있다.

In [24]:
sum(c(1,2,3,4)) # 벡터입력 -> 스칼라출력

[1] 10

In [25]:
mean(c(1,2,3,4)) # 벡터입력 -> 스칼라출력

[1] 2.5

- 아래 함수는 벡터입력-벡터출력 이므로 해당되지 않는다.

In [26]:
sqrt(c(1,2,3,4)) # 벡터입력 -> 벡터출력

[1] 1.000000 1.414214 1.732051 2.000000

## 적용

In [27]:
A

     [,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12  

In [28]:
apply(A, 1, sum)

[1] 10 26 42

In [29]:
apply(A, 1, mean)

[1]  2.5  6.5 10.5

In [30]:
apply(A, 1, min)

[1] 1 5 9

In [31]:
apply(A, 1, max)

[1]  4  8 12

- 사용자가 임의로 정의한 함수도 가능하다.

In [32]:
f = function(a) (min(a)+1)**2 -3

In [33]:
apply(A, 1, f)

[1]  1 33 97

- 숫자 1을 2로 변경하면 특정함수가 각각의 column에 적용된다.

In [34]:
apply(A, 2, f)

[1]  1  6 13 22

In [35]:
apply(A, 2, sum)

[1] 15 18 21 24

In [36]:
apply(A, 2, min)

[1] 1 2 3 4

In [37]:
apply(A, 2, max)

[1]  9 10 11 12

# %>% 연산자($\star\star\star$)
> 아주 중요한 문법이다.

- 아래는 같은 코드이다.

In [38]:
library(tidyverse)

In [39]:
sum(1:10)

[1] 55

In [40]:
1:10 %>% sum()

[1] 55

In [41]:
1:10 %>% sum

[1] 55

- 아래는 같은 코드이다.

In [42]:
myfun = function(x,y) x**2 +y
myfun(2,3)

[1] 7

In [43]:
myfun = function(x,y) x**2 +y
2 %>% myfun(3)

[1] 7

- 아래는 같은 코드이다.

In [44]:
myfun2 = function(x,y,z) x**2 +y*z
myfun2(2,1,1)

[1] 5

In [45]:
myfun2 = function(x,y,z) x**2 +y*z
2 %>% myfun2(1,1)

[1] 5

## 사용하는 이유

- 합성함수 처리가 쉽다.

- 아래는 같은 코드이다.

In [46]:
2:5 %>% log %>% sqrt %>% sum %>% myfun2(1,1) %>% sqrt

[1] 4.440805

In [47]:
sqrt(myfun2(sum(sqrt(log(2:5))), 1, 1))

[1] 4.440805

- 아래와 같은 느낌

$g(h(f(x)))$

$x \to f \to h \to g$

# 시간비교

In [48]:
t1 = Sys.time()
t1

[1] "2021-11-03 20:25:14 KST"

In [49]:
t2 = Sys.time()
t2

[1] "2021-11-03 20:25:14 KST"

In [50]:
t2-t1

Time difference of 0.156733 secs

In [51]:
#collapse-output
A = sample(1:9, size =100*2000000, replace=TRUE)
dim(A) <- c(2000000,100)
A

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 4    5    2    6    5    1    5    6    1    8     <U+22EF> 3     8    
 [2,] 7    3    2    4    5    9    3    1    5    2     <U+22EF> 3     9    
 [3,] 6    8    4    9    3    3    3    7    5    6     <U+22EF> 3     8    
 [4,] 6    5    9    6    7    5    1    6    7    7     <U+22EF> 7     3    
 [5,] 9    9    6    9    5    6    3    6    5    8     <U+22EF> 6     8    
 [6,] 4    4    8    1    7    3    4    9    4    1     <U+22EF> 8     4    
 [7,] 5    6    6    9    4    9    5    1    8    2     <U+22EF> 1     6    
 [8,] 6    8    6    5    6    8    8    2    3    2     <U+22EF> 3     1    
 [9,] 1    5    2    5    2    3    8    5    2    1     <U+22EF> 8     6    
[10,] 3    4    2    9    9    9    5    7    3    4     <U+22EF> 9     3    
[11,] 1    1    2    7    3    3    6    3    1    9     <U+22EF> 1     8    
[12,] 3    6    9    6    9    9    7    2    9    2     <U+22EF> 8

In [52]:
t1=Sys.time()
A %>% apply(1,min) %>% max
t2=Sys.time()
t2-t1

[1] 2

Time difference of 10.82146 secs

In [53]:
t1 = Sys.time()
vec <- c()
for (i in 1:dim(A)[1]) vec[i] <- min(A[i,])
max(vec)
t2=Sys.time()
t2-t1

[1] 2

Time difference of 5.11485 secs

- for문이 더 빠르지만 코드는 apply가 더 간결하다.