In [4]:
#hide
options(jupyter.plot_scale = 3)
options(jupyter.display_mimetypes = c("text/html"))
options(jupyter.rich_display=FALSE)
options(repr.plot.width=6, repr.plot.height=6, repr.plot.res=300)
options(max.print=1000)

# "R : matrix"
> "전북대학교 R입문 7주차 필기"

- toc: true
- branch: master
- badges: true
- comments: true
- author: Kim Jeewoo
- categories: [Introduction to R]
- image: images/r_logo.PNG

# 매트릭스를 선언하는 방법

## 방법1 : row-vector -> rbind

In [6]:
rbind(c(1,2,3,4),c(2,3,4,5))

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 2    3    4    5   

## 방법2 : column-vector -> cbind

In [7]:
cbind(c(1,2,3,4),c(2,3,4,5))

     [,1] [,2]
[1,] 1    2   
[2,] 2    3   
[3,] 3    4   
[4,] 4    5   

# 매트릭스의 차원(dimension)

In [10]:
A = rbind(c(1,2,3,4),c(2,3,4,5))
dim(A)

[1] 2 4

In [16]:
B = cbind(c(1,2,3,4),c(2,3,4,5))
dim(B)

[1] 4 2

- 차원을 바꿀 수도 있다.

In [12]:
B

     [,1] [,2]
[1,] 1    2   
[2,] 2    3   
[3,] 3    4   
[4,] 4    5   

In [14]:
dim(B) = c(2,4)

In [15]:
B

     [,1] [,2] [,3] [,4]
[1,] 1    3    2    4   
[2,] 2    4    3    5   

# 매트릭스의 원소를 뽑는 방법

In [19]:
A = rbind(c(1,2,3,4),c(5,6,7,8),c(9,10,11,12))
A

     [,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12  

In [28]:
A[1,] # 1행을 뽑고싶다.

[1] 1 2 3 4

In [29]:
A[,1] # 1열을 뽑고싶다.

[1] 1 5 9

In [25]:
A[, c(1,4)] # 1열, 4열을 뽑고싶다.

     [,1] [,2]
[1,] 1     4  
[2,] 5     8  
[3,] 9    12  

In [26]:
A[c(1,2),] # 1행, 2행을 뽑고싶다.

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8   

In [27]:
A[2,3]  # 2행3열의 원소를 뽑고싶다.

[1] 7

# apply 함수

```r
apply(matrix, 1, 특정함수)
```

를 쓰면 어떠한 특정한수가 각각의 row에 적용되어서 결과가 array로 저장된다.

여기에서 특정함수는 "벡터입력-스칼라출력"이라고 생각하자, 즉 벡터입력-스칼라입력인 함수를 적용할 수 있다.

In [37]:
sum(c(1,2,3,4)) # 벡터입력 -> 스칼라출력

[1] 10

In [40]:
mean(c(1,2,3,4)) # 벡터입력 -> 스칼라출력

[1] 2.5

- 아래 함수는 벡터입력-벡터출력 이므로 해당되지 않는다.

In [39]:
sqrt(c(1,2,3,4)) # 벡터입력 -> 벡터출력

[1] 1.000000 1.414214 1.732051 2.000000

## 적용

In [41]:
A

     [,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12  

In [42]:
apply(A, 1, sum)

[1] 10 26 42

In [43]:
apply(A, 1, mean)

[1]  2.5  6.5 10.5

In [44]:
apply(A, 1, min)

[1] 1 5 9

In [45]:
apply(A, 1, max)

[1]  4  8 12

- 사용자가 임의로 정의한 함수도 가능하다.

In [46]:
f = function(a) (min(a)+1)**2 -3

In [50]:
apply(A, 1, f)

[1]  1 33 97

- 숫자 1을 2로 변경하면 특정함수가 각각의 column에 적용된다.

In [49]:
apply(A, 2, f)

[1]  1  6 13 22

In [51]:
apply(A, 2, sum)

[1] 15 18 21 24

In [53]:
apply(A, 2, min)

[1] 1 2 3 4

In [54]:
apply(A, 2, max)

[1]  9 10 11 12

# %>% 연산자($\star\star\star$)
> 아주 중요한 문법이다.

- 아래는 같은 코드이다.

In [56]:
sum(1:10)

[1] 55

In [57]:
1:10 %>% sum()

[1] 55

In [58]:
1:10 %>% sum

[1] 55

- 아래는 같은 코드이다.

In [67]:
myfun = function(x,y) x**2 +y
myfun(2,3)

[1] 7

In [68]:
myfun = function(x,y) x**2 +y
2 %>% myfun(3)

[1] 7

- 아래는 같은 코드이다.

In [73]:
myfun2 = function(x,y,z) x**2 +y*z
myfun2(2,1,1)

[1] 5

In [74]:
myfun2 = function(x,y,z) x**2 +y*z
2 %>% myfun2(1,1)

[1] 5

## 사용하는 이유

- 합성함수 처리가 쉽다.

- 아래는 같은 코드이다.

In [79]:
2:5 %>% log %>% sqrt %>% sum %>% myfun2(1,1) %>% sqrt

[1] 4.440805

In [82]:
sqrt(myfun2(sum(sqrt(log(2:5))), 1, 1))

[1] 4.440805

- 아래와 같은 느낌

$g(h(f(x)))$

$x \to f \to h \to g$

# 시간비교

In [98]:
t1 = Sys.time()
t1

[1] "2021-10-25 14:33:29 KST"

In [101]:
t2 = Sys.time()
t2

[1] "2021-10-25 14:33:32 KST"

In [102]:
t2-t1

Time difference of 2.921214 secs

In [131]:
#collapse-output
A = sample(1:9, size =100*2000000, replace=TRUE)
dim(A) <- c(2000000,100)
A

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    5    9    5    9    5    7    4    7    7     <U+22EF> 7     1    
 [2,] 1    2    5    2    4    5    4    7    4    4     <U+22EF> 2     7    
 [3,] 5    4    5    9    9    5    1    7    8    1     <U+22EF> 9     2    
 [4,] 8    4    1    3    5    5    9    6    3    8     <U+22EF> 2     8    
 [5,] 8    5    6    5    9    1    8    6    2    1     <U+22EF> 2     7    
 [6,] 9    5    6    9    3    7    3    8    3    8     <U+22EF> 5     3    
 [7,] 8    7    2    8    7    9    2    2    9    3     <U+22EF> 8     4    
 [8,] 6    7    5    9    7    6    2    8    7    2     <U+22EF> 6     7    
 [9,] 8    6    7    7    7    7    6    4    1    4     <U+22EF> 8     1    
[10,] 2    5    3    4    6    5    4    6    5    7     <U+22EF> 5     5    
[11,] 3    9    4    4    9    8    8    4    8    6     <U+22EF> 8     9    
[12,] 5    4    9    1    6    6    4    3    6    3     <U+22EF> 1

In [134]:
t1=Sys.time()
A %>% apply(1,min) %>% max
t2=Sys.time()
t2-t1

[1] 2

Time difference of 5.181226 secs

In [135]:
t1 = Sys.time()
vec <- c()
for (i in 1:dim(A)[1]) vec[i] <- min(A[i,])
max(vec)
t2=Sys.time()
t2-t1

[1] 2

Time difference of 3.999614 secs

- for문이 더 빠르지만 코드는 apply가 더 간결하다.