In [2]:
#hide
options(jupyter.plot_scale = 3)
options(jupyter.display_mimetypes = c("text/html"))
options(jupyter.rich_display=FALSE)
options(repr.plot.width=6, repr.plot.height=6, repr.plot.res=300)
options(max.print=1000)

# "데이터 타입"
> "전북대학교 R입문 8주차 필기"

- toc: true
- branch: master
- badges: true
- comments: true
- author: Kim Jeewoo
- categories: [Introduction to R]
- image: images/r_logo.PNG

# 데이터 타입

## 수치형(numeric)

- 정수, 실수, 지수 등을 나타내며 실수가 기본형

In [24]:
a=345
mode(a)

[1] "numeric"

In [25]:
a=34.5556
mode(a)

[1] "numeric"

## 논리형(logical)

- 참(TRUE)과 거짓(FALSE)를 나타낸다.

In [26]:
A = TRUE
mode(A)

[1] "logical"

In [27]:
A = F
mode(A)

[1] "logical"

In [28]:
A = T
mode(A)

[1] "logical"

## 문자형(character)

In [29]:
A = "friendship"
mode(A)

[1] "character"

In [30]:
A = "TRUE"
mode(A)

[1] "character"

In [31]:
A = "1"
mode(A)

[1] "character"

## 복소수형(complex)

In [32]:
a = 1+3i
b = 3+7i
a+b

[1] 4+10i

In [33]:
mode(a)

[1] "complex"

In [34]:
mode(a+b)

[1] "complex"

## 정수형(integer)

- 생략

# 데이터 타입 변환

## 첫 번째 방법

In [35]:
a = "1"
mode(a)

[1] "character"

In [40]:
mode(a) <- "numeric"
mode(a)

[1] "numeric"

In [41]:
a

[1] 1

## 두 번째 방법

In [42]:
a = T
as.numeric(a)

[1] 1

In [43]:
a = F
as.numeric(a)

[1] 0

In [44]:
a = -1
as.logical(a)

[1] TRUE

In [45]:
a = 2
as.logical(a)

[1] TRUE

In [46]:
a = 2.22
as.logical(a)

[1] TRUE

In [54]:
a = 0
as.logical(a)

[1] FALSE

- 강제형변환

In [61]:
a = "asdfasfasf"
a = as.numeric(a)

Warning message in eval(expr, envir, enclos):
"강제형변환에 의해 생성된 NA 입니다"


In [62]:
mode(a)

[1] "numeric"

In [63]:
as.logical(a)

[1] NA

In [64]:
a = as.logical(a)
mode(a)

[1] "logical"

In [65]:
as.character(a)

[1] NA

## 서로 다른 형으로 이루어진 벡터의 mode

- 문자형 섞여있으면 모두 문자형으로 바뀐다.

In [66]:
a <- c(1, T, "1")
a

[1] "1"    "TRUE" "1"   

In [70]:
mode(a)

[1] "numeric"

- 문자형이 없으면 모두 numeric형으로 바뀐다.

In [71]:
a <- c(1, T)
a

[1] 1 1

In [69]:
mode(a)

[1] "numeric"

- 서로 다른 형을 가진 벡터를 만들면 한가지 형으로 자동 형 변환이 된다.

- mode가 두 개일 수 없다.

# 과제

In [82]:
A = matrix(1:9, ncol=3, byrow=TRUE)
A

     [,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9   

In [87]:
B = (-A)
B[3,3] = -10
B

     [,1] [,2] [,3]
[1,] -1   -2    -3 
[2,] -4   -5    -6 
[3,] -7   -8   -10 

In [88]:
A + B

     [,1] [,2] [,3]
[1,] 0    0     0  
[2,] 0    0     0  
[3,] 0    0    -1  